name: client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  build_runner: ^2.4.13
  convert: ^3.1.1
  convex_bottom_bar: ^3.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed: ^2.5.7
  go_router: ^14.2.8
  hooks_riverpod: ^2.5.2
  http: ^1.2.2
  image_picker: ^1.0.0
  path: ^1.9.0
  sqflite: ^2.4.0
  syncfusion_flutter_datepicker: ^27.1.52

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
