name: client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  build_runner: ^2.4.13
  convert: ^3.1.1
  convex_bottom_bar: ^3.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.7
  go_router: ^14.2.8
  hooks_riverpod: ^2.5.2
  http: ^1.2.2
  http_parser: ^4.0.2
  image_picker: ^1.0.0
  mime: ^2.0.0
  path: ^1.9.0
  riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  sqflite: ^2.4.0
  syncfusion_flutter_datepicker: ^27.1.52
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
